# Generated by Django 5.2 on 2025-09-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0001_initial'),
        ('subscriptions_api', '0004_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions_api.usersubscription'),
        ),
    ]
