# Generated by Django 5.2.11 on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant al que pertenece este pago', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants_api.tenant'),
        ),
    ]
