# Generated by Django 5.2.11 on 2026-09-13 21:50

import apps.payments_api.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0003_alter_paymentprovider_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(choices=[('azul', 'Azul (RD)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cardnet', 'CardNET (RD)'), ('manual', 'Manual')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Archivo del comprobante (PDF, JPG, PNG o WebP)', storage=apps.payments_api.storage.PaymentProofStorage(), upload_to='proofs')),
                ('file_name', models.CharField(blank=True, help_text='Nombre de archivo original saneado (sin ruta)', max_length=255)),
                ('bank_reference', models.CharField(db_index=True, help_text='Referencia bancaria normalizada de la transferencia/depósito', max_length=255)),
                ('amount_provided', models.DecimalField(decimal_places=2, help_text='Importe declarado por el cliente en el comprobante', max_digits=10)),
                ('decision', models.CharField(choices=[('pending', 'Pendiente de revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], db_index=True, default='pending', help_text='Decisión administrativa sobre este comprobante', max_length=20)),
                ('decision_note', models.TextField(blank=True, help_text='Motivo/nota del administrador (obligatorio en el rechazo)')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha/hora de la revisión (aprobación o rechazo)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(help_text='Pago manual al que corresponde este comprobante', on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='payments_api.payment')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrador que revisó este comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante de pago manual',
                'verbose_name_plural': 'Comprobantes de pago manual',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('decision', 'pending')), fields=('payment',), name='one_pending_proof_per_payment'), models.UniqueConstraint(condition=models.Q(('decision', 'approved')), fields=('payment',), name='one_approved_proof_per_payment')],
            },
        ),
    ]
