# Generated by Django 5.2 on 2025-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='trial_notifications_sent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
