# Generated by Django 5.2 on 2026-02-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de eliminación lógica', null=True),
        ),
    ]
