# Generated by Django 5.2 on 2026-02-18 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0002_initial'),
        ('tenants_api', '0002_tenant_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subdomain'], name='tenants_api_subdoma_a0d20e_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_api_is_acti_55d46d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['deleted_at'], name='tenants_api_deleted_84a2b6_idx'),
        ),
    ]
