# Generated by Django 5.2 on 2025-09-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_api', '0002_tenant_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('standard', 'Standard')], default='free', max_length=20),
        ),
    ]
