# Generated by Django 5.2 on 2025-09-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0004_alter_subscription_plan'),
        ('tenants_api', '0003_tenant_address_tenant_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions_api.subscriptionplan'),
        ),
    ]
