# Generated by Django 5.2.11 on 2026-04-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_api', '0006_tenant_payment_grace_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='grace_period_until',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='last_payment_failed_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='payment_failure_count',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
