# Generated by Django 5.2.11 on 2026-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_api', '0007_remove_tenant_grace_period_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
