# Generated by Django 5.2.11 on 2026-06-27 17:12

from django.db import migrations, models


def migrate_free_plan_type(apps, schema_editor):
    Tenant = apps.get_model('tenants_api', 'Tenant')
    Tenant.objects.filter(plan_type='free').update(plan_type='')


class Migration(migrations.Migration):

    dependencies = [
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_free_plan_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenant',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Pro'), ('premium', 'Business'), ('enterprise', 'Enterprise')], default='', max_length=20),
        ),
    ]
