<<<<<<< HEAD
# Generated by Django 5.2 on 2025-08-06 12:17

import django.db.models.deletion
=======
# Generated by Django 5.2 on 2025-06-18 05:43

import django.db.models.deletion
from django.conf import settings
>>>>>>> origin/master
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_api', '0001_initial'),
<<<<<<< HEAD
        ('roles_api', '0001_initial'),
=======
        ('pos_api', '0001_initial'),
        ('roles_api', '0001_initial'),
        ('services_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> origin/master
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='clients_api.client')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_appointments', to='roles_api.role')),
<<<<<<< HEAD
=======
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='pos_api.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services_api.service')),
                ('stylist', models.ForeignKey(limit_choices_to={'user_roles__role__name': 'stylist'}, on_delete=django.db.models.deletion.CASCADE, related_name='stylist_appointments', to=settings.AUTH_USER_MODEL)),
>>>>>>> origin/master
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-date_time'],
<<<<<<< HEAD
=======
                'unique_together': {('stylist', 'date_time')},
>>>>>>> origin/master
            },
        ),
    ]
