# Generated by Django 5.2 on 2025-12-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_api', '0001_initial'),
        ('clients_api', '0001_initial'),
        ('roles_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='clients_api.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_appointments', to='roles_api.role'),
        ),
    ]
