# Generated by Django 5.2 on 2025-08-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_api', '0001_initial'),
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_for_sale', to='pos_api.sale'),
        ),
    ]
