# Generated by Django 5.2 on 2025-06-14 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0004_alter_appointment_stylist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(limit_choices_to={'userrole__role__name': 'stylist'}, on_delete=django.db.models.deletion.CASCADE, related_name='stylist_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
