# Generated by Django 5.2.1 on 2025-09-10 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0004_appointment_sale'),
        ('roles_api', '0003_alter_role_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_appointments', to='roles_api.role'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
