# Generated by Django 5.2.11 on 2026-05-29 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0008_alter_appointment_status'),
        ('clients_api', '0002_loyaltytransaction'),
        ('pos_api', '0026_add_tenant_to_posconfiguration'),
        ('roles_api', '0005_remove_soporte_role'),
        ('services_api', '0006_alter_service_image_max_length'),
        ('tenants_api', '0010_alter_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='appointment_tenant__5720ea_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'stylist', 'date_time'], name='appointment_tenant__cbf5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date_time'], name='appointment_date_ti_57212a_idx'),
        ),
    ]
