# Generated by Django 5.2.11 on 2026-06-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0010_remove_unique_together'),
        ('settings_api', '0010_add_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_appointments', to='settings_api.branch'),
        ),
    ]
