# Generated by Django 5.2.11 on 2026-07-02 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0011_appointment_branch'),
        ('clients_api', '0004_alter_client_user'),
        ('pos_api', '0032_rename_stripe_field_to_provider_transaction_id'),
        ('roles_api', '0005_remove_soporte_role'),
        ('services_api', '0007_alter_service_unique_together_service_branch_and_more'),
        ('settings_api', '0012_systemsettings_azul_auth1_systemsettings_azul_auth2_and_more'),
        ('tenants_api', '0011_remove_free_plan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'branch', 'date_time'], name='appointment_tenant__000c81_idx'),
        ),
    ]
