# Generated by Django 5.2.11 on 2026-06-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('appointments', 'Citas'), ('employees', 'Empleados'), ('pos', 'POS / Ventas'), ('inventory', 'Inventario'), ('services', 'Servicios'), ('clients', 'Clientes'), ('reports', 'Reportes'), ('settings', 'Configuración'), ('payroll', 'Nómina'), ('subscriptions', 'Suscripciones')], max_length=30, verbose_name='Módulo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('video_url', models.URLField(verbose_name='URL del video (YouTube embed)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL del thumbnail')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Duración (ej: 3:45)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriales',
                'ordering': ['module', 'order'],
            },
        ),
    ]
