# Generated by Django 5.2.11 on 2026-06-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0002_loyaltytransaction'),
        ('settings_api', '0010_add_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_clients', to='settings_api.branch'),
        ),
    ]
