# Generated by Django 5.2 on 2025-12-23 09:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('payroll', 'Nómina'), ('tax_provision', 'Provisión Impuestos'), ('loan_disbursement', 'Desembolso Préstamo'), ('loan_payment', 'Pago Préstamo')], max_length=20)),
                ('reference_id', models.CharField(max_length=50)),
                ('entry_date', models.DateField()),
                ('description', models.TextField()),
                ('debit_account', models.CharField(max_length=20)),
                ('credit_account', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenant', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exported', models.BooleanField(default=False)),
                ('export_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('salary_type', models.CharField(choices=[('fixed', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto (Sueldo + Comisión)')], default='commission', help_text='Tipo de pago: fixed, commission, mixed', max_length=10)),
                ('contractual_monthly_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Salario mensual contractual (fuente de verdad para cálculos de nómina)', max_digits=10)),
                ('salary_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='[DEPRECATED] Usar contractual_monthly_salary. Anteriormente: sueldo quincenal', max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje de comisión (ej: 40.00 para 40%)', max_digits=5)),
                ('payment_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='biweekly', help_text='Frecuencia de pago', max_length=10)),
                ('commission_payment_mode', models.CharField(choices=[('PER_PERIOD', 'Por Período'), ('ON_DEMAND', 'Retiro Libre')], default='PER_PERIOD', help_text='Modo de pago de comisiones: PER_PERIOD (por períodos) u ON_DEMAND (retiro libre)', max_length=12)),
                ('commission_on_demand_since', models.DateField(blank=True, help_text='Fecha desde la cual las comisiones se manejan ON_DEMAND (previene doble pago)', null=True)),
                ('apply_afp', models.BooleanField(default=False, help_text='Aplicar descuento AFP (2.87%)')),
                ('apply_sfs', models.BooleanField(default=False, help_text='Aplicar descuento SFS (3.04%)')),
                ('apply_isr', models.BooleanField(default=False, help_text='Aplicar descuento ISR')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FortnightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de ganancias de la quincena', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_services', models.IntegerField(default=0, help_text='Número de servicios realizados', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de comisiones', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_tips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de propinas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Monto real pagado', max_digits=10, null=True)),
                ('afp_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento AFP (2.87%)', max_digits=10)),
                ('sfs_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento SFS (3.04%)', max_digits=10)),
                ('isr_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento ISR (según escala)', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de descuentos legales', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario neto después de descuentos', max_digits=10)),
                ('payment_reference', models.CharField(blank=True, help_text='Referencia bancaria o número de cheque', max_length=100, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Notas adicionales del pago', null=True)),
                ('is_advance_payment', models.BooleanField(default=False, help_text='Indica si este pago fue realizado antes de la fecha correspondiente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fortnight_year', '-fortnight_number'],
            },
        ),
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('loan_balance_after', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['payment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('afp_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='AFP (2.87%)', max_digits=10)),
                ('sfs_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SFS (3.04%)', max_digits=10)),
                ('isr_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ISR (según escala)', max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
                ('period_year', models.IntegerField()),
                ('period_index', models.IntegerField()),
                ('period_frequency', models.CharField(max_length=10)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('fixed_salary', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto'), ('bonus', 'Bono'), ('adjustment', 'Ajuste')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Monto bruto antes de descuentos', max_digits=10)),
                ('afp_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sfs_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto neto pagado al empleado', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_notes', models.TextField(blank=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión aplicado', max_digits=5, null=True)),
                ('commission_base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto base para cálculo de comisión', max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_year', models.IntegerField()),
                ('period_index', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_services', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_year', '-period_index'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('advance', 'Anticipo de Sueldo'), ('personal_loan', 'Préstamo Personal'), ('emergency', 'Préstamo de Emergencia')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('pending_cancellation', 'Cancelación Pendiente'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('installments', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cancellation_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cancellations', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la ganancia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('earning_type', models.CharField(choices=[('service', 'Servicio'), ('commission', 'Comisión'), ('tip', 'Propina'), ('bonus', 'Bono'), ('adjustment', 'Ajuste')], default='service', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('description', models.TextField(blank=True)),
                ('date_earned', models.DateTimeField(default=django.utils.timezone.now)),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='appointments_api.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
