# Generated by Django 5.2 on 2025-08-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0001_initial'),
        ('services_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_api.service'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees_api.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeservice',
            unique_together={('employee', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'day_of_week', 'start_time')},
        ),
    ]
