# Generated by Django 5.2 on 2025-11-26 09:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0004_initial'),
        ('employees_api', '0001_initial'),
        ('pos_api', '0008_alter_sale_user'),
        ('services_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la ganancia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('earning_type', models.CharField(choices=[('service', 'Servicio'), ('commission', 'Comisión'), ('tip', 'Propina'), ('bonus', 'Bono'), ('adjustment', 'Ajuste')], default='service', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('description', models.TextField(blank=True)),
                ('date_earned', models.DateTimeField(default=django.utils.timezone.now)),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__email']},
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='employees/avatars/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje de comisión (ej: 40.00 para 40%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sueldo fijo mensual', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto (Sueldo + Comisión)')], default='commission', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto real pagado', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Notas adicionales del pago', null=True),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Referencia bancaria o número de cheque', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='total_commissions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de comisiones', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de ganancias de la quincena', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='total_services',
            field=models.IntegerField(default=0, help_text='Número de servicios realizados', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fortnightsummary',
            name='total_tips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de propinas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='fortnightsummary',
            index=models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_4c6166_idx'),
        ),
        migrations.AddIndex(
            model_name='fortnightsummary',
            index=models.Index(fields=['is_paid'], name='employees_a_is_paid_161bbe_idx'),
        ),
        migrations.AddField(
            model_name='earning',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='appointments_api.appointment'),
        ),
        migrations.AddField(
            model_name='earning',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earning',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='earning',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='pos_api.sale'),
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_api.service'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='fortnight_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='employees_api.fortnightsummary'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees_api.employee'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_0a4ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['date_earned'], name='employees_a_date_ea_49e6cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeservice',
            unique_together={('employee', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'day_of_week', 'start_time')},
        ),
    ]
