# Generated by Django 5.2 on 2025-10-06 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0001_initial'),
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='pos_api.sale'),
        ),
    ]
