# Generated by Django 5.2 on 2025-09-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0002_initial'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenants_api.tenant'),
            preserve_default=False,
        ),
    ]
