# Generated by Django 5.2 on 2025-12-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0002_initial'),
        ('pos_api', '0001_initial'),
        ('services_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_api.service'),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortnight_summaries', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='employees_api.advanceloan'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employees_api.advanceloan'),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='payroll_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees_api.fortnightsummary'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='fortnight_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='employees_api.fortnightsummary'),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batches', to='tenants_api.tenant'),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees_api.payrollbatch'),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='tenants_api.tenant'),
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='payroll_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducted_loans', to='employees_api.payrollpayment'),
        ),
        migrations.AddField(
            model_name='payrollpaymentsale',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='employees_api.payrollpayment'),
        ),
        migrations.AddField(
            model_name='payrollpaymentsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='pos_api.sale'),
        ),
        migrations.AddField(
            model_name='periodsummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_summaries', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='periodsummary',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='period_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees_api.periodsummary'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees_api.employee'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_0a4ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['external_id'], name='employees_a_externa_becbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['date_earned'], name='employees_a_date_ea_49e6cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeservice',
            unique_together={('employee', 'service')},
        ),
        migrations.AddIndex(
            model_name='fortnightsummary',
            index=models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_4c6166_idx'),
        ),
        migrations.AddIndex(
            model_name='fortnightsummary',
            index=models.Index(fields=['is_paid'], name='employees_a_is_paid_161bbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fortnightsummary',
            unique_together={('employee', 'fortnight_year', 'fortnight_number')},
        ),
        migrations.AlterUniqueTogether(
            name='loanpayment',
            unique_together={('loan', 'payment_number')},
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['tenant', 'status'], name='employees_a_tenant__1c8da7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['batch_number'], name='employees_a_batch_n_1c5df4_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['created_at'], name='employees_a_created_568aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['employee', 'period_year', 'period_index'], name='employees_a_employe_e8b900_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['tenant', 'paid_at'], name='employees_a_tenant__636e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['payment_type'], name='employees_a_payment_83ca1f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['idempotency_key'], name='employees_a_idempot_9f7716_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['status'], name='employees_a_status_7a5a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='loandeduction',
            index=models.Index(fields=['payroll_payment'], name='employees_a_payroll_23170f_idx'),
        ),
        migrations.AddIndex(
            model_name='loandeduction',
            index=models.Index(fields=['loan'], name='employees_a_loan_id_6759c9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentsale',
            index=models.Index(fields=['payment'], name='employees_a_payment_1949a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentsale',
            index=models.Index(fields=['sale'], name='employees_a_sale_id_d15fc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollpaymentsale',
            unique_together={('payment', 'sale')},
        ),
        migrations.AddIndex(
            model_name='periodsummary',
            index=models.Index(fields=['employee', 'frequency', 'period_year', 'period_index'], name='employees_a_employe_aefebf_idx'),
        ),
        migrations.AddIndex(
            model_name='periodsummary',
            index=models.Index(fields=['is_paid'], name='employees_a_is_paid_b8ea03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='periodsummary',
            unique_together={('employee', 'frequency', 'period_year', 'period_index')},
        ),
        migrations.AddIndex(
            model_name='payrollbatchitem',
            index=models.Index(fields=['batch', 'status'], name='employees_a_batch_i_8cb246_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatchitem',
            index=models.Index(fields=['employee'], name='employees_a_employe_ab02ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollbatchitem',
            unique_together={('batch', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'day_of_week', 'start_time')},
        ),
    ]
