# Generated by Django 5.2 on 2026-02-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0002_initial'),
        ('services_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_api.service'),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortnight_summaries', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='fortnight_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='employees_api.fortnightsummary'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees_api.employee'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_0a4ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['date_earned'], name='employees_a_date_ea_49e6cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeservice',
            unique_together={('employee', 'service')},
        ),
        migrations.AddIndex(
            model_name='fortnightsummary',
            index=models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_4c6166_idx'),
        ),
        migrations.AddIndex(
            model_name='fortnightsummary',
            index=models.Index(fields=['is_paid'], name='employees_a_is_paid_161bbe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fortnightsummary',
            unique_together={('employee', 'fortnight_year', 'fortnight_number')},
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'day_of_week', 'start_time')},
        ),
    ]
