# Generated by Django 5.2 on 2026-01-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollpayment',
            name='payment_type',
            field=models.CharField(choices=[('fixed_salary', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto'), ('bonus', 'Bono'), ('adjustment', 'Ajuste'), ('SCHEDULED', 'Pago Programado'), ('PAYROLL', 'Nómina')], max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('paid', 'Pagado')], default='open', max_length=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='employees_api.employee')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('employee', 'start_date', 'end_date')},
            },
        ),
    ]
