# Generated by Django 5.2 on 2025-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión (ej: 40.00 para 40%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sueldo fijo mensual', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto (Sueldo + Comisión)')], default='commission', max_length=10),
        ),
    ]
