# Generated by Django 5.2.1 on 2025-09-08 03:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0004_appointment_sale'),
        ('employees_api', '0003_employee_tenant'),
        ('pos_api', '0002_alter_saledetail_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_type', models.CharField(choices=[('service', 'Servicio'), ('commission', 'Comisión'), ('tip', 'Propina'), ('bonus', 'Bono'), ('adjustment', 'Ajuste')], default='service', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión', max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('date_earned', models.DateTimeField(default=django.utils.timezone.now)),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='appointments_api.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='employees_api.employee')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='pos_api.sale')),
            ],
            options={
                'ordering': ['-date_earned'],
                'indexes': [models.Index(fields=['employee', 'fortnight_year', 'fortnight_number'], name='employees_a_employe_0a4ad1_idx'), models.Index(fields=['date_earned'], name='employees_a_date_ea_49e6cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='FortnightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_services', models.IntegerField(default=0)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortnight_summaries', to='employees_api.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fortnight_year', '-fortnight_number'],
                'unique_together': {('employee', 'fortnight_year', 'fortnight_number')},
            },
        ),
    ]
