# Generated by Django 5.2 on 2025-11-30 23:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0003_add_salary_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='fixed_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='biweekly', help_text='Frecuencia de pago', max_length=10),
        ),
        migrations.CreateModel(
            name='PeriodSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_year', models.IntegerField()),
                ('period_index', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_services', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_summaries', to='employees_api.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_index'],
                'indexes': [models.Index(fields=['employee', 'frequency', 'period_year', 'period_index'], name='employees_a_employe_aefebf_idx'), models.Index(fields=['is_paid'], name='employees_a_is_paid_b8ea03_idx')],
                'unique_together': {('employee', 'frequency', 'period_year', 'period_index')},
            },
        ),
    ]
