# Generated by Django 5.2 on 2026-01-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0004_alter_payrollpayment_payment_type_payrollperiod'),
        ('pos_api', '0002_remove_legacy_payroll_models'),
    ]

    operations = [
        # Migración vacía - los modelos legacy ya fueron eliminados del código
    ]
