# Generated by Django 5.2 on 2025-12-01 01:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0004_initial'),
        ('employees_api', '0004_remove_employee_commission_rate_and_more'),
        ('pos_api', '0009_merge_0002_add_sale_status_0008_alter_sale_user'),
        ('tenants_api', '0002_tenant_trial_notifications_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='earning',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['external_id'], name='employees_a_externa_becbe6_idx'),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batches', to='tenants_api.tenant'),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees_api.payrollbatch'),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='period_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees_api.periodsummary'),
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['tenant', 'status'], name='employees_a_tenant__1c8da7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['batch_number'], name='employees_a_batch_n_1c5df4_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['created_at'], name='employees_a_created_568aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatchitem',
            index=models.Index(fields=['batch', 'status'], name='employees_a_batch_i_8cb246_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollbatchitem',
            index=models.Index(fields=['employee'], name='employees_a_employe_ab02ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollbatchitem',
            unique_together={('batch', 'employee')},
        ),
    ]
