# Generated by Django 5.2 on 2025-12-06 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0005_payrollbatch_payrollbatchitem_earning_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortnightsummary',
            name='afp_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento AFP (2.87%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='isr_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento ISR (según escala)', max_digits=10),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario neto después de descuentos', max_digits=10),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='sfs_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento SFS (3.04%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='fortnightsummary',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de descuentos legales', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='afp_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='AFP (2.87%)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='isr_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ISR (según escala)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollbatchitem',
            name='sfs_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SFS (3.04%)', max_digits=10),
        ),
    ]
