# Generated by Django 5.2 on 2026-01-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0006_safe_remove_legacy_models'),
    ]

    operations = [
    ]
