# Generated by Django 5.2 on 2026-01-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0008_final_state_sync'),
    ]

    operations = [
    ]
