# Generated by Django 5.2 on 2026-01-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0009_final_cleanup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fortnightsummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fortnightsummary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='fortnightsummary',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='loanpayment',
            name='payroll_payment',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payrollbatch',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='payrollbatchitem',
            name='batch',
        ),
        migrations.AlterUniqueTogether(
            name='payrollbatchitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payrollbatchitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrollbatchitem',
            name='period_summary',
        ),
        migrations.AlterUniqueTogether(
            name='periodsummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='periodsummary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='periodsummary',
            name='paid_by',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
        migrations.DeleteModel(
            name='FortnightSummary',
        ),
        migrations.DeleteModel(
            name='PayrollBatch',
        ),
        migrations.DeleteModel(
            name='PayrollBatchItem',
        ),
        migrations.DeleteModel(
            name='PeriodSummary',
        ),
    ]
