# Generated by Django 5.2 on 2025-12-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0010_phase2_models'),
    ]

    operations = [
    ]
