# Generated by Django 5.2 on 2025-12-11 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0011_auto_20251210_2316'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortnightsummary',
            name='loan_deductions',
        ),
        migrations.AddField(
            model_name='advanceloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceloan',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advance_loans', to='employees_api.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='loan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employees_api.advanceloan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='payroll_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees_api.fortnightsummary'),
        ),
        migrations.AlterUniqueTogether(
            name='loanpayment',
            unique_together={('loan', 'payment_number')},
        ),
    ]
