# Generated by Django 5.2 on 2025-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0012_remove_fortnightsummary_loan_deductions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortnightsummary',
            name='is_advance_payment',
            field=models.BooleanField(default=False, help_text='Indica si este pago fue realizado antes de la fecha correspondiente'),
        ),
        migrations.AlterField(
            model_name='advanceloan',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20),
        ),
    ]
