# Generated by Django 5.2 on 2026-02-18 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0014_payrollperiod_fixed_salary_snapshot_and_more'),
        ('tenants_api', '0002_tenant_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant'], name='employees_a_tenant__ba34e7_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employees_a_is_acti_daee8a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'is_active'], name='employees_a_tenant__41ff29_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldeduction',
            index=models.Index(fields=['period'], name='employees_a_period__45dbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['employee'], name='employees_a_employe_c27d6c_idx'),
        ),
    ]
