# Generated by Django 5.2 on 2025-12-15 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0014_add_loan_cancellation_process'),
        ('pos_api', '0012_alter_sale_earnings_generated_and_more'),
        ('tenants_api', '0002_tenant_trial_notifications_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_year', models.IntegerField()),
                ('period_index', models.IntegerField()),
                ('period_frequency', models.CharField(max_length=10)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('fixed_salary', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto'), ('bonus', 'Bono'), ('adjustment', 'Ajuste')], max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Monto bruto antes de descuentos', max_digits=10)),
                ('afp_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sfs_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Monto neto pagado al empleado', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_notes', models.TextField(blank=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión aplicado', max_digits=5, null=True)),
                ('commission_base_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto base para cálculo de comisión', max_digits=10, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='employees_api.employee')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='tenants_api.tenant')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPaymentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='employees_api.payrollpayment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='pos_api.sale')),
            ],
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['employee', 'period_year', 'period_index'], name='employees_a_employe_e8b900_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['tenant', 'paid_at'], name='employees_a_tenant__636e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['payment_type'], name='employees_a_payment_83ca1f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentsale',
            index=models.Index(fields=['payment'], name='employees_a_payment_1949a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpaymentsale',
            index=models.Index(fields=['sale'], name='employees_a_sale_id_d15fc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollpaymentsale',
            unique_together={('payment', 'sale')},
        ),
    ]
