# Generated by Django 5.2 on 2025-12-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0015_payrollpayment_payrollpaymentsale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_payment_mode',
            field=models.CharField(choices=[('PER_PERIOD', 'Por Período'), ('ON_DEMAND', 'Retiro Libre')], default='PER_PERIOD', help_text='Modo de pago de comisiones: PER_PERIOD (por períodos) u ON_DEMAND (retiro libre)', max_length=12),
        ),
    ]
