# Generated by Django 5.2.11 on 2026-02-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0015_employee_employees_a_tenant__ba34e7_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__email'], 'permissions': [('view_employee_payroll', 'Can view employee payroll'), ('manage_employee_loans', 'Can manage employee loans')]},
        ),
    ]
