# Generated by Django 5.2 on 2025-12-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0016_add_commission_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission_on_demand_since',
            field=models.DateField(blank=True, help_text='Fecha desde la cual las comisiones se manejan ON_DEMAND (previene doble pago)', null=True),
        ),
    ]
