# Generated by Django 5.2.11 on 2026-07-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0024_refact_employee_model_20250704_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='legacy_specialty_text',
            field=models.CharField(blank=True, help_text='Texto de specialty original en migración', max_length=100, null=True),
        ),
    ]
