# Generated by Django 5.2.11 on 2026-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0026_remove_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(blank=True, choices=[('barber', 'Barbero (Corte caballero)'), ('stylist', 'Estilista (Corte dama)'), ('manicurist', 'Manicurista'), ('pedicurist', 'Pedicurista'), ('colorist', 'Colorista'), ('braider', 'Trencista'), ('eyebrow', 'Cejas / Pestañas'), ('makeup', 'Maquilladora'), ('massage', 'Masajista'), ('barber_stylist', 'Barbero / Estilista'), ('receptionist', 'Recepcionista'), ('cashier', 'Cajero / Cajera'), ('manager', 'Administrador / Gerente'), ('general', 'General / Multipropósito'), ('other', 'Otro')], help_text='Profesión principal del empleado (ej.: barbero, estilista, manicurista, etc.)', max_length=100),
        ),
    ]
