# Generated by Django 5.2.11 on 2026-07-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0027_alter_employee_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutos de tardanza registrados al marcar asistencia'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='commission_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión vigente al crear período', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments', models.PositiveIntegerField(default=1)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paid', 'Pagado')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees_api.employee')),
            ],
        ),
    ]
