# Generated by Django 5.2.11 on 2026-07-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0029_add_loan_type_to_loan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeService',
        ),
    ]
