# Generated by Django 5.2 on 2025-12-19 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0017_add_commission_on_demand_since'),
        ('employees_api', '0999_add_earning_constraint'),
    ]

    operations = [
    ]
