# Generated by Django 5.2 on 2025-12-19 11:28

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '1000_merge_20251219_0728'),
        ('tenants_api', '0002_tenant_trial_notifications_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['idempotency_key'], name='employees_a_idempot_9f7716_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollpayment',
            index=models.Index(fields=['status'], name='employees_a_status_7a5a1b_idx'),
        ),
    ]
