# Generated by Django 5.2 on 2025-12-19 12:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '1001_add_payment_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('loan_balance_after', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='employees_api.advanceloan')),
                ('payroll_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducted_loans', to='employees_api.payrollpayment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payroll_payment'], name='employees_a_payroll_23170f_idx'), models.Index(fields=['loan'], name='employees_a_loan_id_6759c9_idx')],
            },
        ),
    ]
