# Generated by Django 5.2 on 2026-01-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='period',
        ),
    ]
