# Generated by Django 5.2 on 2025-06-20 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0002_alter_appointment_sale'),
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='appointments_api.appointment'),
        ),
    ]
