# Generated by Django 5.2 on 2025-10-29 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('buy_x_get_y', 'Buy X Get Y Free'), ('combo', 'Combo Offer')], max_length=20)),
                ('conditions', models.JSONField(default=dict, blank=True, help_text='Valid JSON object with promotion conditions')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PosConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('tax_included', models.BooleanField(default=False)),
                ('receipt_template', models.TextField(default='default')),
                ('receipt_footer', models.TextField(blank=True)),
                ('auto_print_receipt', models.BooleanField(default=False)),
                ('require_customer', models.BooleanField(default=False)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Configuration',
                'verbose_name_plural': 'POS Configurations',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('template_used', models.CharField(default='default', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('printed_count', models.IntegerField(default=0)),
                ('last_printed', models.DateTimeField(blank=True, null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='pos_api.sale')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counts', to='pos_api.cashregister')),
            ],
            options={
                'verbose_name': 'Cash Count',
                'verbose_name_plural': 'Cash Counts',
                'unique_together': {('cash_register', 'denomination')},
            },
        ),
    ]
