# Generated by Django 5.2 on 2026-01-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0010_add_employee_to_saledetail'),
        ('pos_api', '0002_remove_legacy_payroll_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Empleado que ejecuta este servicio específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_details', to='employees_api.employee'),
        ),
    ]
