# Generated by Django 5.2 on 2025-11-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_promotion_posconfiguration_receipt_cashcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='conditions',
            field=models.JSONField(default=dict),
        ),
    ]
