# Generated by Django 5.2 on 2026-02-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0005_payrollperiod_approved_at_payrollperiod_approved_by_and_more'),
        ('pos_api', '0003_sale_cash_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='employees_api.payrollperiod'),
        ),
    ]
