# Generated by Django 5.2 on 2025-11-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0004_update_cash_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-opened_at']},
        ),
        migrations.RenameIndex(
            model_name='cashregister',
            new_name='pos_api_cas_user_id_927bec_idx',
            old_name='pos_api_cas_user_id_opened_idx',
        ),
        migrations.RenameIndex(
            model_name='cashregister',
            new_name='pos_api_cas_is_open_44120f_idx',
            old_name='pos_api_cas_is_open_idx',
        ),
    ]
