# Generated by Django 5.2 on 2025-11-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_add_employee_to_sale'),
        ('pos_api', '0005_alter_cashregister_options_and_more'),
    ]

    operations = [
    ]
