# Generated by Django 5.2 on 2025-11-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_add_sale_status'),
        ('pos_api', '0008_alter_sale_user'),
    ]

    operations = [
    ]
