# Generated by Django 5.2 on 2026-02-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0008_remove_sale_pos_api_sal_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de comisión calculado al momento de la venta', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de comisión vigente al momento de la venta', max_digits=5, null=True),
        ),
    ]
