# Generated by Django 5.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0009_merge_0002_add_sale_status_0008_alter_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='earnings_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='earnings_reverted',
            field=models.BooleanField(default=False),
        ),
    ]