# Generated by Django 5.2 on 2026-02-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0009_sale_commission_amount_snapshot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleRefund',
        ),
    ]
