# Generated by Django 5.2 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0010_add_earnings_tracking'),
    ]

    operations = [
        # Índices para Sale - consultas más frecuentes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_sale_tenant_date_idx ON pos_api_sale (user_id, date_time);",
            reverse_sql="DROP INDEX IF EXISTS pos_sale_tenant_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_sale_employee_date_idx ON pos_api_sale (employee_id, date_time);",
            reverse_sql="DROP INDEX IF EXISTS pos_sale_employee_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_sale_status_date_idx ON pos_api_sale (status, date_time);",
            reverse_sql="DROP INDEX IF EXISTS pos_sale_status_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_sale_date_only_idx ON pos_api_sale (date(date_time));",
            reverse_sql="DROP INDEX IF EXISTS pos_sale_date_only_idx;"
        ),
        
        # Índices para SaleDetail - relaciones frecuentes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_saledetail_sale_content_idx ON pos_api_saledetail (sale_id, content_type_id);",
            reverse_sql="DROP INDEX IF EXISTS pos_saledetail_sale_content_idx;"
        ),
        
        # Índices para CashRegister - consultas por usuario y fecha
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_cashregister_user_date_idx ON pos_api_cashregister (user_id, opened_at);",
            reverse_sql="DROP INDEX IF EXISTS pos_cashregister_user_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pos_cashregister_open_date_idx ON pos_api_cashregister (is_open, opened_at);",
            reverse_sql="DROP INDEX IF EXISTS pos_cashregister_open_date_idx;"
        ),
    ]