# Generated by Django 5.2 on 2026-02-16 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0001_initial'),
        ('employees_api', '0014_payrollperiod_fixed_salary_snapshot_and_more'),
        ('pos_api', '0010_delete_salerefund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date_time', 'user'], name='pos_api_sal_date_ti_a16fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['date_time', 'employee'], name='pos_api_sal_date_ti_b1a630_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='pos_api_sal_status_7ff5cf_idx'),
        ),
    ]
