# Generated by Django 5.2 on 2025-12-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0011_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='earnings_generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='earnings_reverted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
