# Generated by Django 5.2 on 2026-02-26 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0001_initial'),
        ('employees_api', '0015_employee_employees_a_tenant__ba34e7_idx_and_more'),
        ('pos_api', '0013_remove_sale_pos_api_sal_tenant_date_idx'),
        ('tenants_api', '0004_tenant_locale_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant'], name='pos_api_sal_tenant__5fdd7b_idx'),
        ),
    ]
