# Generated by Django 5.2.11 on 2026-02-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0014_sale_pos_api_sal_tenant__5fdd7b_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_time'], 'permissions': [('refund_sale', 'Can refund sales'), ('view_financial_reports', 'Can view financial reports')], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
