# Generated by Django 5.2.11 on 2026-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0017_remove_posconfiguration_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='posconfiguration',
            name='rnc',
            field=models.CharField(blank=True, help_text='RNC/Cédula para comprobantes fiscales (RD)', max_length=30, null=True),
        ),
    ]
