# Generated by Django 5.2.11 on 2026-05-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0020_cashregister_tenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashregister',
            new_name='pos_api_cas_tenant__911952_idx',
            old_name='pos_api_cash_tenant_i_abc123',
        ),
    ]
