# Generated by Django 5.2.11 on 2026-05-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0021_rename_pos_api_cash_tenant_i_abc123_pos_api_cas_tenant__911952_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.TextField(blank=True, default='', help_text='Motivo del descuento (requerido para descuentos > umbral)'),
        ),
        migrations.AlterField(
            model_name='cashcount',
            name='denomination',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='cashcount',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='final_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='commission_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de comisión calculado al momento de la venta', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
