# Generated by Django 5.2.11 on 2026-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0024_payment_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
