# Generated by Django 5.2.11 on 2026-05-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0025_alter_saledetail_object_id'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='posconfiguration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_configs', to='tenants_api.tenant'),
        ),
    ]
