# Generated by Django 5.2.11 on 2026-06-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0026_add_tenant_to_posconfiguration'),
        ('settings_api', '0010_add_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_cash_registers', to='settings_api.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_sales', to='settings_api.branch'),
        ),
    ]
