# Generated by Django 5.2.11 on 2026-06-18 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_api', '0004_alter_client_user'),
        ('employees_api', '0023_attendancerecord_is_justified_and_more'),
        ('pos_api', '0029_add_promotion_fk_to_sale'),
        ('settings_api', '0011_barbershopsettings_whatsapp_enabled_and_more'),
        ('tenants_api', '0010_alter_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', '-date_time'], name='pos_api_sal_tenant__06f29c_idx'),
        ),
    ]
