# Generated by Django 5.2.11 on 2026-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0031_sale_coupon_code_coupon_sale_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment provider (Stripe, CardNET, etc.)', max_length=255, null=True),
        ),
    ]
