# Generated by Django 5.2.11 on 2026-09-13 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0032_rename_stripe_field_to_provider_transaction_id'),
        ('settings_api', '0015_add_payment_provider_credentials'),
        ('tenants_api', '0011_remove_free_plan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('tenant', 'user', 'branch'), name='unique_open_register_per_user_branch'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('is_open', True)), fields=('tenant', 'user'), name='unique_open_register_per_user_no_branch'),
        ),
    ]
