# docker-compose.minimal.yml - Solo DB y Redis
version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
    command: >
      postgres 
      -c shared_buffers=128MB 
      -c effective_cache_size=256MB 
      -c work_mem=4MB 
      -c max_connections=30

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    command: redis-server --maxmemory 32mb --maxmemory-policy allkeys-lru

volumes:
  postgres_data:

# Ejecuta Django y Celery nativamente:
# python manage.py runserver
# celery -A backend worker --loglevel=info --concurrency=1