# Generated by Django 5.2 on 2025-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
        ('roles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='assigned_users', through='roles_api.UserRole', to='roles_api.role'),
        ),
    ]
