# Generated by Django 5.2 on 2025-08-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_initial'),
        ('roles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='roles_api.UserRole', to='roles_api.role'),
        ),
    ]
