# Generated by Django 5.2 on 2026-02-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginaudit',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loginaudit',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
