# Generated by Django 5.2 on 2025-12-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='refresh_token',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='token_jti',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
