# Generated by Django 5.2 on 2025-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'Super Admin'), ('Client-Admin', 'Client Admin'), ('Client-Staff', 'Client Staff')], max_length=20, null=True),
        ),
    ]
