# Generated by Django 5.2 on 2026-02-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_alter_accesslog_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='refresh_token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='token_jti',
            field=models.TextField(unique=True),
        ),
    ]
