# Generated by Django 5.2 on 2025-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SuperAdmin', 'Super Admin'), ('Client-Admin', 'Client Admin'), ('Client-Staff', 'Client Staff'), ('Estilista', 'Estilista'), ('Cajera', 'Cajera'), ('Manager', 'Manager'), ('Utility', 'Utility')], max_length=20, null=True),
        ),
    ]
