# Generated by Django 5.2 on 2026-02-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0005_alter_activesession_refresh_token_and_more'),
        ('roles_api', '0002_initial'),
        ('tenants_api', '0003_tenant_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', False), ('is_superuser', True), _connector='OR'), name='user_must_have_tenant_or_be_superuser', violation_error_message='Los usuarios no superadmin deben tener un tenant asignado.'),
        ),
    ]
