# Generated by Django 5.2 — merged migration
# Combines: 0006_add_tenant_constraint + 0006_email_unique_per_tenant

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0005_alter_activesession_refresh_token_and_more'),
        ('roles_api', '0002_initial'),
        ('tenants_api', '0003_tenant_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('tenant__isnull', False),
                    ('is_superuser', True),
                    _connector='OR',
                ),
                name='user_must_have_tenant_or_be_superuser',
                violation_error_message='Los usuarios no superadmin deben tener un tenant asignado.',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'tenant')},
        ),
    ]
