# Generated by Django 5.2.11 on 2026-05-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_user_unique_email_for_global_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
