# Generated by Django 5.2.11 on 2026-06-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_remove_unique_together'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='tenants_api.tenant'),
        ),
        migrations.AddField(
            model_name='loginaudit',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_audits', to='tenants_api.tenant'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['tenant', 'timestamp'], name='auth_api_ac_tenant__c8fc80_idx'),
        ),
        migrations.AddIndex(
            model_name='loginaudit',
            index=models.Index(fields=['tenant', 'timestamp'], name='auth_api_lo_tenant__a927ae_idx'),
        ),
    ]
