# Generated by Django 5.2.11 on 2026-07-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0012_add_tenant_fk_to_login_audit_access_log'),
        ('roles_api', '0005_remove_soporte_role'),
        ('tenants_api', '0011_remove_free_plan_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email', 'tenant'), name='unique_email_per_tenant', violation_error_message='Ya existe un usuario con este email en este negocio.'),
        ),
    ]
