# Generated by Django 5.2.11 on 2026-09-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0014_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_for_global_users',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_email_per_tenant',
        ),
    ]
