# Generated by Django 5.2 on 2025-10-06 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio por Empleado',
                'verbose_name_plural': 'Servicios por Empleado',
            },
        ),
        migrations.CreateModel(
            name='StylistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default='00:30:00', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Servicio de Estilista',
                'verbose_name_plural': 'Servicios de Estilistas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duración en minutos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='services', to='roles_api.role')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
