<<<<<<< HEAD
# Generated by Django 5.2 on 2025-08-06 12:17
=======
# Generated by Django 5.2 on 2025-06-12 11:54
>>>>>>> origin/master

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='services', to='roles_api.role')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='StylistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default='00:30:00', validators=[django.core.validators.MinValueValidator(1)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to='services_api.service')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de Estilista',
                'verbose_name_plural': 'Servicios de Estilistas',
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='services_ap_name_8473b4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_ap_is_acti_304631_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stylistservice',
            unique_together={('stylist', 'service')},
        ),
    ]
