# Generated by Django 5.2 on 2026-02-02 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0002_initial'),
        ('roles_api', '0002_initial'),
        ('tenants_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duración en minutos')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='services', to='roles_api.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='employees_api.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_employees', to='services_api.service')),
            ],
            options={
                'verbose_name': 'Servicio por Empleado',
                'verbose_name_plural': 'Servicios por Empleado',
            },
        ),
        migrations.CreateModel(
            name='StylistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default='00:30:00', validators=[django.core.validators.MinValueValidator(1)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to='services_api.service')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de Estilista',
                'verbose_name_plural': 'Servicios de Estilistas',
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='services_ap_name_8473b4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_ap_is_acti_304631_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant'], name='services_ap_tenant__620ca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceemployee',
            unique_together={('service', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='stylistservice',
            unique_together={('stylist', 'service')},
        ),
    ]
