# Generated by Django 5.2 on 2025-09-02 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_api', '0003_alter_role_scope'),
        ('services_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants_api.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant'], name='services_ap_tenant__620ca5_idx'),
        ),
    ]
