# Generated by Django 5.2 on 2025-10-06 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0003_initial'),
        ('services_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tenants_api.tenant'),
        ),
        migrations.AddField(
            model_name='serviceemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='employees_api.employee'),
        ),
        migrations.AddField(
            model_name='serviceemployee',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_employees', to='services_api.service'),
        ),
        migrations.AddField(
            model_name='stylistservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to='services_api.service'),
        ),
        migrations.AddField(
            model_name='stylistservice',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='services_ap_name_8473b4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_ap_is_acti_304631_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant'], name='services_ap_tenant__620ca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceemployee',
            unique_together={('service', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='stylistservice',
            unique_together={('stylist', 'service')},
        ),
    ]
