# Generated by Django 5.2 on 2026-02-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['name'],
                'unique_together': {('name', 'tenant')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='services', to='services_api.servicecategory'),
        ),
    ]
