# Generated by Django 5.2 on 2026-02-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0002_remove_service_category_servicecategory_and_more'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['tenant'], name='services_ap_tenant__ecffa3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active'], name='services_ap_is_acti_ff8314_idx'),
        ),
    ]
