# Generated by Django 5.2.1 on 2025-09-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0002_service_tenant_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duración en minutos'),
        ),
    ]
