# Generated by Django 5.2.11 on 2026-02-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0003_servicecategory_services_ap_tenant__ecffa3_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('set_employee_price', 'Can set employee-specific prices'), ('assign_employees', 'Can assign employees to services')], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
