# Generated by Django 5.2 on 2025-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0003_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
