# Generated by Django 5.2 on 2025-09-24 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0004_earning_fortnightsummary'),
        ('services_api', '0004_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_services', to='employees_api.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_employees', to='services_api.service')),
            ],
            options={
                'verbose_name': 'Servicio por Empleado',
                'verbose_name_plural': 'Servicios por Empleado',
                'unique_together': {('service', 'employee')},
            },
        ),
    ]
