# Generated by Django 5.2.11 on 2026-06-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_api', '0006_alter_service_image_max_length'),
        ('settings_api', '0011_barbershopsettings_whatsapp_enabled_and_more'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_services', to='settings_api.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('name', 'tenant', 'branch')},
        ),
    ]
