# Generated by Django 5.2.11 on 2026-04-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0005_subscriptionplan_commercial_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Creacion'), ('updated', 'Actualizacion'), ('deleted', 'Eliminacion'), ('renewed', 'Renovacion'), ('cancelled', 'Cancelacion'), ('expired', 'Expiracion'), ('payment_failed', 'Fallo de pago'), ('payment_successful', 'Pago exitoso'), ('plan_changed', 'Cambio de plan'), ('trial_started', 'Inicio de prueba'), ('trial_ended', 'Fin de prueba'), ('subscription_suspended', 'Suspension de suscripcion'), ('subscription_resumed', 'Reanudacion de suscripcion'), ('subscription_paused', 'Pausa de suscripcion'), ('subscription_reactivated', 'Reactivacion de suscripcion')], help_text='Action performed on the subscription', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='allows_multiple_branches',
            field=models.BooleanField(default=False, help_text='Permite multiples sucursales'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Professional'), ('standard', 'Business'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], help_text='Name of the subscription plan', max_length=100, unique=True),
        ),
    ]
