# Generated by Django 5.2.11 on 2026-04-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0007_alter_subscription_unique_together_and_more'),
        ('tenants_api', '0007_remove_tenant_grace_period_until_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_active_subscription_per_tenant',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('tenant', 'plan')},
        ),
    ]
