# Generated by Django 5.2.11 on 2026-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0008_remove_subscription_unique_active_subscription_per_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Esencial'), ('standard', 'Crecimiento'), ('premium', 'Escala'), ('enterprise', 'Enterprise')], help_text='Name of the subscription plan', max_length=100, unique=True),
        ),
    ]
