# Generated by Django 5.2.11 on 2026-06-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0012_usersubscription_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Mensual'), ('year', 'Anual')], default='month', help_text='Ciclo de facturacion: mensual o anual', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio anual del plan', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_annual_price_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Price ID (ej: price_...) para cobro recurrente anual', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_interval',
            field=models.CharField(choices=[('month', 'Mensual'), ('year', 'Anual')], default='month', help_text='Ciclo de facturacion: mensual o anual', max_length=20),
        ),
    ]
