# Generated by Django 5.2.11 on 2026-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0014_add_promotional_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_annual_plan_id',
            field=models.CharField(blank=True, db_index=True, help_text='PayPal Plan ID (ej: P-...) para cobro anual', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, db_index=True, help_text='PayPal Plan ID (ej: P-...) para cobro mensual', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_product_id',
            field=models.CharField(blank=True, db_index=True, help_text='PayPal Product ID (ej: PROD-...) para producto base', max_length=120, null=True),
        ),
    ]
