# Generated by Django 5.2.11 on 2026-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0015_subscriptionplan_paypal_annual_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
