# Generated by Django 5.2 on 2025-09-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='role',
            name='module',
            field=models.CharField(blank=True, help_text='solo si scope=MODULE', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('TENANT', 'Tenant'), ('MODULE', 'ModulE')], default='TENANT', max_length=20),
        ),
        migrations.AddField(
            model_name='userrole',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_user_roles', to='tenants_api.tenant'),
        ),
    ]
