# Generated by Django 5.2 on 2025-09-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_api', '0002_role_limits_role_module_role_scope_userrole_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('TENANT', 'Tenant'), ('MODULE', 'Module')], default='TENANT', max_length=20),
        ),
    ]
