# Generated by Django 5.2.11 on 2026-05-08 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_api', '0003_cajera_pos_cashregister_permissions'),
        ('tenants_api', '0009_plan_public_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrole',
            name='roles_api_u_user_id_31ebd3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role', 'tenant'], name='roles_api_u_user_id_10943b_idx'),
        ),
    ]
