# Generated by Django 5.2.11 on 2026-02-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('adjust_stock', 'Can adjust product stock')]},
        ),
    ]
