# Generated by Django 5.2.11 on 2026-03-20 10:38

import django.db.models.deletion
from django.db import migrations, models


def clear_category_text(apps, schema_editor):
    """Limpiar valores de texto en category antes de convertir a FK"""
    schema_editor.connection.cursor().execute(
        "ALTER TABLE inventory_api_product ALTER COLUMN category DROP NOT NULL"
    )
    schema_editor.connection.cursor().execute(
        "UPDATE inventory_api_product SET category = NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0002_alter_product_options'),
        ('tenants_api', '0005_tenant_access_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(clear_category_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory_api.productcategory'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['tenant'], name='inventory_a_tenant__e332d9_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='inventory_a_is_acti_4f3fe6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'tenant')},
        ),
    ]
