# Generated by Django 5.2.1 on 2025-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0002_product_tenant_supplier_tenant_alter_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
