# Generated by Django 5.2.11 on 2026-06-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0005_product_branch'),
        ('settings_api', '0010_add_brand_colors'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_per_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_barcode_per_tenant',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'branch', 'is_active'], name='inventory_a_tenant__b200de_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('sku', 'tenant'), name='unique_sku_per_tenant_global'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('sku', 'tenant', 'branch'), name='unique_sku_per_tenant_branch'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), ('branch__isnull', True)), fields=('barcode', 'tenant'), name='unique_barcode_per_tenant_global'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), ('branch__isnull', False)), fields=('barcode', 'tenant', 'branch'), name='unique_barcode_per_tenant_branch'),
        ),
    ]
