# Generated by Django 5.2.11 on 2026-05-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('auth_api', '0009_user_business_role'),
        ('roles_api', '0003_cajera_pos_cashregister_permissions'),
        ('tenants_api', '0009_plan_public_names'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('email',), name='unique_email_for_global_users', violation_error_message='Ya existe un superusuario con este email.'),
        ),
    ]
