# Generated by Django 5.2 on 2025-12-23 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='BarberSaaS', max_length=255, verbose_name='Nombre de la plataforma')),
                ('support_email', models.EmailField(default='soporte@barbersaas.com', max_length=254, verbose_name='Email de soporte')),
                ('max_tenants', models.PositiveIntegerField(default=100, verbose_name='Máximo de clientes')),
                ('trial_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Días de prueba')),
                ('default_currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda por defecto')),
                ('platform_domain', models.CharField(blank=True, max_length=255, verbose_name='Dominio principal')),
                ('supported_languages', models.JSONField(default=list, verbose_name='Idiomas habilitados')),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Comisión de plataforma (%)')),
                ('basic_plan_max_employees', models.PositiveIntegerField(default=5, verbose_name='Plan básico - máx. empleados')),
                ('premium_plan_max_employees', models.PositiveIntegerField(default=25, verbose_name='Plan premium - máx. empleados')),
                ('enterprise_plan_max_employees', models.PositiveIntegerField(default=999, verbose_name='Plan enterprise - máx. empleados')),
                ('stripe_enabled', models.BooleanField(default=True, verbose_name='Stripe habilitado')),
                ('paypal_enabled', models.BooleanField(default=False, verbose_name='PayPal habilitado')),
                ('twilio_enabled', models.BooleanField(default=False, verbose_name='SMS (Twilio) habilitado')),
                ('sendgrid_enabled', models.BooleanField(default=True, verbose_name='Email (SendGrid) habilitado')),
                ('aws_s3_enabled', models.BooleanField(default=True, verbose_name='Almacenamiento (AWS S3) habilitado')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('auto_suspend_expired', models.BooleanField(default=True, verbose_name='Suspender automáticamente vencidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='BarbershopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('default_fixed_salary', models.DecimalField(decimal_places=2, default=1200000.0, max_digits=10)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 19.00 for 19%)', max_digits=5)),
                ('service_discount_limit', models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum discount percentage', max_digits=5)),
                ('cancellation_policy_hours', models.IntegerField(default=24, help_text='Hours before appointment for free cancellation')),
                ('late_arrival_grace_minutes', models.IntegerField(default=15, help_text='Grace period for late arrivals')),
                ('booking_advance_days', models.IntegerField(default=30, help_text='How many days in advance can clients book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_settings', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Barbershop Settings',
                'verbose_name_plural': 'Barbershop Settings',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants_api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de impuestos')),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=100, verbose_name='Zona horaria')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='Horario de atención')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias generales')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='Logo del negocio')),
                ('theme', models.CharField(default='light', max_length=50, verbose_name='Tema visual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings_api.branch')),
            ],
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_branch_per_tenant'),
        ),
    ]
