# Generated by Django 5.2 on 2025-08-12 04:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de impuestos')),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=100, verbose_name='Zona horaria')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='Horario de atención')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias generales')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='Logo del negocio')),
                ('theme', models.CharField(default='light', max_length=50, verbose_name='Tema visual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_api.branch', verbose_name='Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='SettingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.JSONField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_api.setting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('branch',), name='unique_setting_per_branch'),
        ),
    ]
