# Generated by Django 5.2 on 2025-10-06 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Nombre del negocio')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de impuestos')),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=100, verbose_name='Zona horaria')),
                ('business_hours', models.JSONField(blank=True, default=dict, verbose_name='Horario de atención')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Preferencias generales')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='Logo del negocio')),
                ('theme', models.CharField(default='light', max_length=50, verbose_name='Tema visual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='BarberSaaS', max_length=255, verbose_name='Nombre de la plataforma')),
                ('support_email', models.EmailField(default='soporte@barbersaas.com', max_length=254, verbose_name='Email de soporte')),
                ('max_tenants', models.PositiveIntegerField(default=100, verbose_name='Máximo de clientes')),
                ('trial_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Días de prueba')),
                ('default_currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda por defecto')),
                ('platform_domain', models.CharField(blank=True, max_length=255, verbose_name='Dominio principal')),
                ('supported_languages', models.JSONField(default=list, verbose_name='Idiomas habilitados')),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Comisión de plataforma (%)')),
                ('basic_plan_max_employees', models.PositiveIntegerField(default=5, verbose_name='Plan básico - máx. empleados')),
                ('premium_plan_max_employees', models.PositiveIntegerField(default=25, verbose_name='Plan premium - máx. empleados')),
                ('enterprise_plan_max_employees', models.PositiveIntegerField(default=999, verbose_name='Plan enterprise - máx. empleados')),
                ('stripe_enabled', models.BooleanField(default=True, verbose_name='Stripe habilitado')),
                ('paypal_enabled', models.BooleanField(default=False, verbose_name='PayPal habilitado')),
                ('twilio_enabled', models.BooleanField(default=False, verbose_name='SMS (Twilio) habilitado')),
                ('sendgrid_enabled', models.BooleanField(default=True, verbose_name='Email (SendGrid) habilitado')),
                ('aws_s3_enabled', models.BooleanField(default=True, verbose_name='Almacenamiento (AWS S3) habilitado')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('auto_suspend_expired', models.BooleanField(default=True, verbose_name='Suspender automáticamente vencidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
