# Generated by Django 5.2 on 2025-09-02 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='BarberSaaS', max_length=255, verbose_name='Nombre de la plataforma')),
                ('support_email', models.EmailField(default='soporte@barbersaas.com', max_length=254, verbose_name='Email de soporte')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('default_currency', models.CharField(default='USD', max_length=10, verbose_name='Moneda por defecto')),
                ('max_tenants', models.PositiveIntegerField(default=100, verbose_name='Máximo de clientes')),
                ('backup_frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=20, verbose_name='Frecuencia de respaldo')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('auto_suspend_expired', models.BooleanField(default=True, verbose_name='Suspender automáticamente vencidos')),
                ('trial_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Días de prueba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
