# Generated by Django 5.2 on 2026-01-06 18:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0001_initial'),
        ('tenants_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100)),
                ('setting_type', models.CharField(choices=[('critical', 'Crítico'), ('sensitive', 'Sensible'), ('cosmetic', 'Cosmético')], max_length=20)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('impact_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_changes', to='tenants_api.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'setting_type'], name='settings_ap_tenant__51cecf_idx'), models.Index(fields=['created_at'], name='settings_ap_created_7b511a_idx')],
            },
        ),
    ]
