# Generated by Django 5.2 on 2025-06-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='settings_api.branch', verbose_name='Sucursal'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('branch',), name='unique_setting_per_branch'),
        ),
    ]
