# Generated by Django 5.2 on 2025-10-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0002_initial'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingauditlog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='settingauditlog',
            name='setting',
        ),
        migrations.RemoveConstraint(
            model_name='setting',
            name='unique_setting_per_branch',
        ),
        migrations.AlterField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenants_api.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='settings_api.branch'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_branch_per_tenant'),
        ),
        migrations.DeleteModel(
            name='SettingAuditLog',
        ),
    ]
