# Generated by Django 5.2 on 2025-11-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0003_remove_settingauditlog_changed_by_and_more'),
        ('tenants_api', '0002_tenant_trial_notifications_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbershopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('default_fixed_salary', models.DecimalField(decimal_places=2, default=1200000.0, max_digits=10)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 19.00 for 19%)', max_digits=5)),
                ('service_discount_limit', models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum discount percentage', max_digits=5)),
                ('cancellation_policy_hours', models.IntegerField(default=24, help_text='Hours before appointment for free cancellation')),
                ('late_arrival_grace_minutes', models.IntegerField(default=15, help_text='Grace period for late arrivals')),
                ('booking_advance_days', models.IntegerField(default=30, help_text='How many days in advance can clients book')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_settings', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Barbershop Settings',
                'verbose_name_plural': 'Barbershop Settings',
            },
        ),
    ]
