# Generated by Django 5.2.11 on 2026-04-12 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0005_systemsettings_login_lockout_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'Configuracion del Sistema', 'verbose_name_plural': 'Configuraciones del Sistema'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, verbose_name='Horario de atencion'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='auto_suspend_expired',
            field=models.BooleanField(default=True, verbose_name='Suspender automaticamente vencidos'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='basic_plan_max_employees',
            field=models.PositiveIntegerField(default=5, verbose_name='Plan basico - max. empleados'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='enterprise_plan_max_employees',
            field=models.PositiveIntegerField(default=999, verbose_name='Plan enterprise - max. empleados'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_tenants',
            field=models.PositiveIntegerField(default=100, verbose_name='Maximo de clientes'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Comision de plataforma (%)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='premium_plan_max_employees',
            field=models.PositiveIntegerField(default=25, verbose_name='Plan premium - max. empleados'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='trial_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Dias de prueba'),
        ),
    ]
