# Generated by Django 5.2.11 on 2026-05-08 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0006_alter_systemsettings_options_alter_setting_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarbershopSettings',
        ),
    ]
