# Generated by Django 5.2.11 on 2026-05-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0007_delete_barbershopsettings'),
        ('tenants_api', '0004_tenant_locale_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarbershopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_settings', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Barbershop Settings',
                'verbose_name_plural': 'Barbershop Settings',
            },
        ),
    ]
