# Generated by Django 5.2.11 on 2026-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0009_add_fr_pt_de_to_supported_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopsettings',
            name='accent_color',
            field=models.CharField(default='#059669', help_text='Color de acento (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='primary_color',
            field=models.CharField(default='#2563EB', help_text='Color primario (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='secondary_color',
            field=models.CharField(default='#4F46E5', help_text='Color secundario (hex)', max_length=7),
        ),
    ]
