# Generated by Django 5.2.11 on 2026-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0010_add_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopsettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='whatsapp_instance_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='whatsapp_status',
            field=models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado')], default='disconnected', max_length=50),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
