# Generated by Django 5.2.11 on 2026-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0011_barbershopsettings_whatsapp_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='azul_auth1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Azul Auth1 (usuario)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azul_auth2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Azul Auth2 (password)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azul_cert_key',
            field=models.TextField(blank=True, help_text='Certificado PEM para autenticación SSL mutua (opcional en JSON mode)', verbose_name='Azul cert/key (PEM)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azul_enabled',
            field=models.BooleanField(default=False, verbose_name='Azul habilitado'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azul_merchant_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Azul Merchant ID'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azul_sandbox',
            field=models.BooleanField(default=True, verbose_name='Azul sandbox'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='azul_store_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Azul Store ID'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='platform_name',
            field=models.CharField(default='Auron Suite', max_length=255, verbose_name='Nombre de la plataforma'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='support_email',
            field=models.EmailField(default='soporte@auronsuite.com', max_length=254, verbose_name='Email de soporte'),
        ),
    ]
