# Generated by Django 5.2.11 on 2026-07-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0012_systemsettings_azul_auth1_systemsettings_azul_auth2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershopsettings',
            name='currency',
            field=models.CharField(default='DOP', max_length=3),
        ),
    ]
