# Generated by Django 5.2.11 on 2026-08-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_api', '0014_barbershopsettings_whatsapp_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershopsettings',
            name='active_payment_provider',
            field=models.CharField(blank=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='azul_auth1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='azul_auth2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='azul_cert_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='azul_merchant_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='azul_store_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='cardnet_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='cardnet_merchant_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='cardnet_terminal_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='payment_sandbox',
            field=models.BooleanField(default=True, help_text='Modo sandbox/pruebas'),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='paypal_client_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='barbershopsettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='barbershopsettings',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
