# Generated by Django 5.2 on 2026-01-01 18:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_api', '0004_alter_payrollpayment_payment_type_payrollperiod'),
        ('tenants_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_year', models.IntegerField()),
                ('period_index', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierto - Acumulando deuda'), ('READY', 'Listo para pago'), ('PAID', 'Pagado')], default='OPEN', max_length=10)),
                ('fixed_salary_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('afp_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sfs_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='employees_api.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants_api.tenant')),
            ],
            options={
                'ordering': ['-period_year', '-period_index'],
            },
        ),
        migrations.CreateModel(
            name='SettlementEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_api.earning')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='payroll_api.payrollsettlement')),
            ],
        ),
        migrations.AddIndex(
            model_name='payrollsettlement',
            index=models.Index(fields=['employee', 'status'], name='payroll_api_employe_84909a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollsettlement',
            index=models.Index(fields=['tenant', 'status'], name='payroll_api_tenant__2a9511_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollsettlement',
            index=models.Index(fields=['period_year', 'period_index'], name='payroll_api_period__70d506_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollsettlement',
            unique_together={('employee', 'frequency', 'period_year', 'period_index')},
        ),
        migrations.AlterUniqueTogether(
            name='settlementearning',
            unique_together={('settlement', 'earning')},
        ),
    ]
