# Generated by Django 5.2 on 2026-01-08 13:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0010_add_employee_to_saledetail'),
        ('payroll_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsettlement',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario por comisión calculado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollsettlement',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario total bruto (fijo + comisión)', max_digits=10),
        ),
        migrations.CreateModel(
            name='MonthlyLegalDeductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_monthly_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('afp_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sfs_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_in_settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll_api.payrollsettlement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_deductions', to='employees_api.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='payroll_api_employe_676708_idx')],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
