# Generated by Django 5.2 on 2026-01-09 10:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0010_add_employee_to_saledetail'),
        ('payroll_api', '0002_alter_payrollsettlement_commission_amount_and_more'),
        ('tenants_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_year', models.IntegerField()),
                ('period_index', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('PAID', 'Pagado')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants_api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('calculation_breakdown', models.JSONField(default=dict, help_text='Detalle completo del cálculo')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bonuses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('legal_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees_api.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants_api.tenant')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_api.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPaymentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_notes', models.TextField(blank=True)),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_new', to='payroll_api.payrollcalculation')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_payroll_payments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants_api.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'paid_at'], name='payroll_api_tenant__c434d8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['tenant', 'status'], name='payroll_api_tenant__92992a_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['period_year', 'period_index'], name='payroll_api_period__bf593a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together={('tenant', 'frequency', 'period_year', 'period_index')},
        ),
        migrations.AddIndex(
            model_name='payrollcalculation',
            index=models.Index(fields=['employee', 'period', 'is_current'], name='payroll_api_employe_2738c9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcalculation',
            index=models.Index(fields=['tenant', 'period'], name='payroll_api_tenant__0f9d80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcalculation',
            unique_together={('employee', 'period', 'version')},
        ),
    ]
