# Generated by Django 5.2 on 2025-08-17 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Fallo de inicio de sesión'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('ROLE_ASSIGN', 'Asignación de rol'), ('ROLE_REMOVE', 'Remoción de rol'), ('PERMISSION_GRANT', 'Concesión de permiso'), ('PERMISSION_REVOKE', 'Revocación de permiso'), ('SETTING_UPDATE', 'Actualización de configuración'), ('SUBSCRIPTION_CREATE', 'Creación de suscripción'), ('SUBSCRIPTION_UPDATE', 'Actualización de suscripción'), ('SUBSCRIPTION_CANCEL', 'Cancelación de suscripción'), ('SUBSCRIPTION_RENEW', 'Renovación de suscripción'), ('MFA_ENABLE', 'Activación de MFA'), ('MFA_DISABLE', 'Desactivación de MFA'), ('ADMIN_ACTION', 'Acción administrativa')], help_text='Tipo de acción realizada', max_length=50)),
                ('description', models.TextField(help_text='Descripción detallada de la acción')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto relacionado', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del cliente')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la acción')),
                ('source', models.CharField(choices=[('AUTH', 'Autenticación'), ('ROLES', 'Roles y permisos'), ('SETTINGS', 'Configuración'), ('SUBSCRIPTIONS', 'Suscripciones'), ('USERS', 'Usuarios'), ('SYSTEM', 'Sistema')], default='SYSTEM', help_text='Origen del log', max_length=50)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de objeto relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_api_a_timesta_9d4473_idx'), models.Index(fields=['user', 'timestamp'], name='audit_api_a_user_id_224977_idx'), models.Index(fields=['action', 'timestamp'], name='audit_api_a_action_922d70_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_api_a_content_d23054_idx')],
            },
        ),
    ]
