# Generated by Django 5.2 on 2025-10-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('VIEW', 'Visualización'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Fallo de inicio de sesión'), ('PASSWORD_CHANGE', 'Cambio de contraseña'), ('ROLE_ASSIGN', 'Asignación de rol'), ('ROLE_REMOVE', 'Remoción de rol'), ('PERMISSION_GRANT', 'Concesión de permiso'), ('PERMISSION_REVOKE', 'Revocación de permiso'), ('SETTING_UPDATE', 'Actualización de configuración'), ('SUBSCRIPTION_CREATE', 'Creación de suscripción'), ('SUBSCRIPTION_UPDATE', 'Actualización de suscripción'), ('SUBSCRIPTION_CANCEL', 'Cancelación de suscripción'), ('SUBSCRIPTION_RENEW', 'Renovación de suscripción'), ('MFA_ENABLE', 'Activación de MFA'), ('MFA_DISABLE', 'Desactivación de MFA'), ('ADMIN_ACTION', 'Acción administrativa'), ('INTEGRATION_ERROR', 'Error de integración'), ('PERFORMANCE_ALERT', 'Alerta de rendimiento'), ('SYSTEM_ERROR', 'Error del sistema'), ('STRIPE_ERROR', 'Error de Stripe'), ('PAYPAL_ERROR', 'Error de PayPal'), ('TWILIO_ERROR', 'Error de Twilio'), ('SENDGRID_ERROR', 'Error de SendGrid')], help_text='Tipo de acción realizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source',
            field=models.CharField(choices=[('AUTH', 'Autenticación'), ('ROLES', 'Roles y permisos'), ('SETTINGS', 'Configuración'), ('SUBSCRIPTIONS', 'Suscripciones'), ('USERS', 'Usuarios'), ('SYSTEM', 'Sistema'), ('INTEGRATIONS', 'Integraciones'), ('PERFORMANCE', 'Rendimiento')], default='SYSTEM', help_text='Origen del log', max_length=50),
        ),
    ]
