# Generated by Django 5.2.11 on 2026-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_financial_reports', 'Can view financial reports'), ('view_employee_reports', 'Can view employee reports'), ('view_sales_reports', 'Can view sales reports'), ('view_kpi_dashboard', 'Can view KPI dashboard'), ('view_advanced_analytics', 'Can view advanced analytics')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
