# Generated by Django 5.2 on 2026-02-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0007_add_audit_fields_to_sale'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_api_sal_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_api_sal_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_api_sal_created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='salerefund',
            name='pos_api_sal_refund_date_idx',
        ),
    ]
