# Generated by Django 5.2 on 2026-02-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0012_add_tenant_to_sale'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_api_sal_tenant_date_idx',
        ),
    ]
