# Generated by Django 5.2.11 on 2026-04-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0016_posconfiguration_rnc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posconfiguration',
            name='rnc',
        ),
    ]
