# Generated by Django 5.2.11 on 2026-05-08 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0018_add_rnc_field_with_nullable'),
        ('tenants_api', '0009_plan_public_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='tenants_api.tenant'),
        ),
    ]
