# Generated by Django 5.2.11 on 2026-06-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0027_cashregister_branch_sale_branch'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='company_name',
            field=models.CharField(blank=True, help_text='Razón Social del cliente facturado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='ncf',
            field=models.CharField(blank=True, db_index=True, help_text='Número de Comprobante Fiscal generado', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='ncf_type',
            field=models.CharField(blank=True, help_text='Tipo de comprobante (B01, B02, etc.)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='rnc',
            field=models.CharField(blank=True, help_text='RNC o Cédula del cliente facturado', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='NCFSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('01', 'Crédito Fiscal (B01)'), ('02', 'Consumidor Final (B02)'), ('14', 'Regímenes Especiales (B14)'), ('15', 'Gubernamentales (B15)')], default='02', max_length=2)),
                ('prefix', models.CharField(default='B', max_length=3)),
                ('start_sequence', models.PositiveIntegerField(default=1)),
                ('end_sequence', models.PositiveIntegerField()),
                ('current_sequence', models.PositiveIntegerField(default=1)),
                ('expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncf_sequences', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Secuencia NCF',
                'verbose_name_plural': 'Secuencias NCF',
                'ordering': ['type', '-is_active', '-created_at'],
                'unique_together': {('tenant', 'type', 'prefix', 'start_sequence')},
            },
        ),
    ]
