# Generated by Django 5.2.11 on 2026-06-17 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0028_sale_company_name_sale_ncf_sale_ncf_type_sale_rnc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos_api.promotion'),
        ),
        migrations.AddField(
            model_name='sale',
            name='promotion_name',
            field=models.CharField(blank=True, default='', help_text='Nombre de la promoción al momento de la venta', max_length=255),
        ),
    ]
