# Generated by Django 5.2.11 on 2026-06-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0030_add_sale_tenant_date_time_idx'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='coupon_code',
            field=models.CharField(blank=True, default='', help_text='Código del cupón al momento de la venta', max_length=50),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Límite de usos totales del cupón', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos_api.coupon'),
        ),
    ]
