# Generated by Django 5.2.11 on 2026-08-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendErrorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(default='ERROR', max_length=16)),
                ('type', models.CharField(default='EVENT', max_length=32)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('module', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=64, null=True)),
                ('trace_id', models.CharField(blank=True, max_length=64, null=True)),
                ('incident_id', models.CharField(blank=True, max_length=32, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, default='', max_length=32)),
                ('browser', models.CharField(blank=True, default='', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'telemetry_frontend_error_event',
                'indexes': [models.Index(fields=['timestamp'], name='telemetry_f_timesta_4fac27_idx'), models.Index(fields=['severity'], name='telemetry_f_severit_380cf2_idx'), models.Index(fields=['module'], name='telemetry_f_module_048fcd_idx')],
            },
        ),
    ]
