# Generated by Django 5.2 on 2025-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Creación'), ('updated', 'Actualización'), ('deleted', 'Eliminación'), ('renewed', 'Renovación'), ('cancelled', 'Cancelación'), ('expired', 'Expiración'), ('payment_failed', 'Fallo de pago'), ('payment_successful', 'Pago exitoso'), ('plan_changed', 'Cambio de plan'), ('trial_started', 'Inicio de prueba'), ('trial_ended', 'Fin de prueba'), ('subscription_suspended', 'Suspensión de suscripción'), ('subscription_resumed', 'Reanudación de suscripción'), ('subscription_paused', 'Pausa de suscripción'), ('subscription_reactivated', 'Reactivación de suscripción')], help_text='Action performed on the subscription', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription Audit Log',
                'verbose_name_plural': 'Subscription Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Plan Básico'), ('standard', 'Plan Estándar'), ('premium', 'Plan Premium'), ('enterprise', 'Plan Empresarial')], help_text='Name of the subscription plan', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_month', models.PositiveIntegerField(default=1, help_text='Duration in month for the subscription plan')),
                ('is_active', models.BooleanField(default=True)),
                ('max_employees', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
