# Generated by Django 5.2 on 2025-10-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('free', 'Plan Gratuito'), ('basic', 'Plan Básico'), ('standard', 'Plan Estándar'), ('premium', 'Plan Premium'), ('enterprise', 'Plan Empresarial')], help_text='Name of the subscription plan', max_length=100, unique=True),
        ),
    ]
