# Generated by Django 5.2 on 2025-09-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
