# Generated by Django 5.2 on 2025-10-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0003_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='allows_multiple_branches',
            field=models.BooleanField(default=False, help_text='Permite múltiples sucursales'),
        ),
    ]
