# Generated by Django 5.2 on 2025-07-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0004_subscriptionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionauditlog',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='subscriptions_api.usersubscription'),
            preserve_default=False,
        ),
    ]
