# Generated by Django 5.2 on 2025-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0005_subscriptionauditlog_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
    ]
