# Generated by Django 5.2.11 on 2026-04-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0006_alter_subscriptionauditlog_action_and_more'),
        ('tenants_api', '0006_tenant_payment_grace_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='unique_active_subscription_per_tenant'),
        ),
    ]
