# Generated by Django 5.2 on 2025-07-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0006_usersubscription_auto_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
