# Generated by Django 5.2 on 2025-07-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0007_alter_usersubscription_auto_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict),
        ),
    ]
