# Generated by Django 5.2 on 2025-07-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0008_subscriptionplan_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basico'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], help_text='Name of the subscription plan', max_length=100, unique=True),
        ),
    ]
