# Generated by Django 5.2.11 on 2026-05-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0011_plan_public_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que se solicitó la cancelación. Si está seteado, la suscripción expirará en end_date.', null=True),
        ),
    ]
