# Generated by Django 5.2.11 on 2026-06-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_api', '0013_subscription_billing_interval_and_more'),
        ('tenants_api', '0010_alter_tenant_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField(help_text='Número de meses gratis otorgados')),
                ('reason', models.TextField(blank=True, help_text='Motivo del crédito (ej. campaña Instagram, referido, etc.)')),
                ('campaign_tag', models.CharField(blank=True, help_text='Tag opcional para agrupar por campaña (ej. INSTAGRAM2026, TIKTOK10)', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='Cuándo se aplicó el crédito', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotional_credits', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_credits', to='tenants_api.tenant')),
            ],
            options={
                'verbose_name': 'Crédito Promocional',
                'verbose_name_plural': 'Créditos Promocionales',
                'ordering': ['-created_at'],
            },
        ),
    ]
