# Generated by Django 5.2 on 2026-02-22 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0003_unique_payment_intent'),
        ('subscriptions_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_api_stripe__ab4de6_idx',
            old_name='billing_api_stripe_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='processedstripeevent',
            new_name='billing_api_stripe__97a584_idx',
            old_name='billing_api_stripe_idx',
        ),
        migrations.RenameIndex(
            model_name='processedstripeevent',
            new_name='billing_api_event_t_752c82_idx',
            old_name='billing_api_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationalert',
            new_name='billing_api_severit_e8263b_idx',
            old_name='billing_api_alert_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationalert',
            new_name='billing_api_created_4ae005_idx',
            old_name='billing_api_alert_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reconciliationlog',
            new_name='billing_api_status_c2bbec_idx',
            old_name='billing_api_recon_status_idx',
        ),
    ]
