# Generated by Django 5.2.11 on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0005_invoice_billing_api_user_id_879871_idx_and_more'),
        ('tenants_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant al que pertenece esta factura', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants_api.tenant'),
        ),
    ]
