# Generated by Django 5.2.11 on 2026-05-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0007_processedpaypalevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='processedpaypalevent',
            new_name='billing_api_paypal__bd2fbf_idx',
            old_name='billing_api_paypal_event_id_idx',
        ),
        migrations.RenameIndex(
            model_name='processedpaypalevent',
            new_name='billing_api_event_t_1ffbfd_idx',
            old_name='billing_api_paypal_event_type_idx',
        ),
    ]
