# Generated by Django 5.2.11 on 2026-06-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0010_add_paypal_order_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_api_paypal__192c8d_idx',
            old_name='billing_api_invoice_paypal_order_id_idx',
        ),
    ]
