# Generated by Django 5.2.11 on 2026-06-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0012_add_paypal_order_id_unique'),
        ('payments_api', '0003_alter_paymentprovider_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Referencia al registro unificado de pago en payments_api', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments_api.payment'),
        ),
    ]
