# Generated by Django 5.2 on 2026-02-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0005_add_tenant_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appointment_tenant__010a99_idx',
            old_name='appt_tenant_dt_idx',
        ),
    ]
