# Generated by Django 5.2.11 on 2026-02-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0006_rename_appt_tenant_dt_idx_appointment_tenant__010a99_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_time'], 'permissions': [('cancel_appointment', 'Can cancel appointments'), ('complete_appointment', 'Can mark appointments as complete')], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
    ]
