# Generated by Django 5.2.11 on 2026-02-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_api', '0007_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=10),
        ),
    ]
