# Generated by Django 5.2.11 on 2026-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0011_rename_billing_api_invoice_paypal_order_id_idx_billing_api_paypal__192c8d_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_api_paypal__192c8d_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='PayPal order ID para idempotencia a nivel DB', max_length=255, null=True, unique=True),
        ),
    ]
