# Generated by Django 5.2 on 2026-02-02 06:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_type', models.CharField(choices=[('fixed', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto (Sueldo + Comisión)')], default='commission', max_length=10)),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Sueldo fijo mensual', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=40.0, help_text='Porcentaje de comisión (ej: 40.00 para 40%)', max_digits=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FortnightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de ganancias de la quincena', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_services', models.IntegerField(default=0, help_text='Número de servicios realizados', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_commissions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de comisiones', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_tips', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de propinas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Monto real pagado', max_digits=10, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Referencia bancaria o número de cheque', max_length=100, null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Notas adicionales del pago', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fortnight_year', '-fortnight_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
            ],
            options={
                'verbose_name': 'Payment Receipt',
                'verbose_name_plural': 'Payment Receipts',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la ganancia', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('earning_type', models.CharField(choices=[('service', 'Servicio'), ('commission', 'Comisión'), ('tip', 'Propina'), ('bonus', 'Bono'), ('adjustment', 'Ajuste')], default='service', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('description', models.TextField(blank=True)),
                ('date_earned', models.DateTimeField(default=django.utils.timezone.now)),
                ('fortnight_year', models.IntegerField()),
                ('fortnight_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='appointments_api.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
