# Generated by Django 5.2 on 2026-02-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0008_employeecompensationhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecompensationhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeecompensationhistory',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='fortnightsummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fortnightsummary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='fortnightsummary',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='fortnight_summary',
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.DeleteModel(
            name='EmployeeCompensationHistory',
        ),
        migrations.DeleteModel(
            name='FortnightSummary',
        ),
        migrations.DeleteModel(
            name='PaymentReceipt',
        ),
    ]
