# Generated by Django 5.2 on 2026-02-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0009_remove_employeecompensationhistory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Indica si el período está finalizado y no debe recalcularse'),
        ),
    ]
