# Generated by Django 5.2 on 2026-02-16 09:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0012_unique_refund_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompensationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('fixed', 'Sueldo Fijo'), ('commission', 'Comisión'), ('mixed', 'Mixto (Sueldo + Comisión)')], max_length=10)),
                ('fixed_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('effective_date', models.DateField(help_text='Fecha desde la cual aplican estas condiciones')),
                ('end_date', models.DateField(blank=True, help_text='Fecha hasta la cual aplicaron estas condiciones (null = vigente)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_reason', models.TextField(blank=True)),
                ('employee_snapshot', models.JSONField(default=dict, help_text='Snapshot completo del empleado al momento del cambio')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='commissionadjustment',
            new_name='employees_a_payroll_a07c03_idx',
            old_name='employees_a_payroll_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionadjustment',
            new_name='employees_a_sale_id_95bebd_idx',
            old_name='employees_a_sale_id_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionadjustment',
            new_name='employees_a_tenant__d88f22_idx',
            old_name='employees_a_tenant_idx',
        ),
        migrations.AddField(
            model_name='payrolldeduction',
            name='installments',
            field=models.IntegerField(default=1, help_text='Número de cuotas para el préstamo', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='employeecompensationhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_changes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeecompensationhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_history', to='employees_api.employee'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationhistory',
            index=models.Index(fields=['employee', 'effective_date'], name='employees_a_employe_3157e1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationhistory',
            index=models.Index(fields=['employee', 'end_date'], name='employees_a_employe_faf59c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecompensationhistory',
            index=models.Index(fields=['effective_date'], name='employees_a_effecti_ae7ed1_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeecompensationhistory',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('effective_date')), _connector='OR'), name='valid_date_range'),
        ),
    ]
