# Generated by Django 5.2 on 2026-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0013_employeecompensationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='fixed_salary_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salario fijo vigente al crear período', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='payment_type_snapshot',
            field=models.CharField(blank=True, help_text='Tipo de pago vigente al crear período', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='deduction_type',
            field=models.CharField(choices=[('tax', 'Impuesto'), ('social_security', 'Seguro Social'), ('health_insurance', 'Seguro Médico'), ('advance', 'Anticipo de Sueldo'), ('loan', 'Préstamo Personal'), ('emergency_loan', 'Préstamo de Emergencia'), ('other', 'Otro')], max_length=20),
        ),
    ]
