# Generated by Django 5.2.11 on 2026-02-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0017_attendancerecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='employees_a_employe_227330_idx',
            old_name='employees_a_employe_e9f98d_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='employees_a_status_8bad28_idx',
            old_name='employees_a_status_f2353a_idx',
        ),
    ]
