# Generated by Django 5.2.11 on 2026-05-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0020_add_payroll_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, choices=[('barber', 'Barbero (Corte caballero)'), ('stylist', 'Estilista (Corte dama)'), ('manicurist', 'Manicurista'), ('pedicurist', 'Pedicurista'), ('colorist', 'Colorista'), ('braider', 'Trencista'), ('eyebrow', 'Cejas / Pestañas'), ('makeup', 'Maquilladora'), ('massage', 'Masajista'), ('barber_stylist', 'Barbero / Estilista'), ('general', 'General / Multipropósito'), ('other', 'Otro')], max_length=100),
        ),
    ]
