# Generated by Django 5.2.11 on 2026-06-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0021_add_specialty_choices'),
        ('settings_api', '0010_add_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_employees', to='settings_api.branch'),
        ),
    ]
