# Generated by Django 5.2.11 on 2026-07-05 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0023_attendancerecord_is_justified_and_more'),
        ('settings_api', '0013_alter_barbershopsettings_currency'),
        ('tenants_api', '0011_remove_free_plan_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='specialty',
        ),
        migrations.AddField(
            model_name='employee',
            name='legacy_specialty_text',
            field=models.CharField(blank=True, help_text='Campo transitorio para migración - texto de la especialidad anterior', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profession',
            field=models.CharField(blank=True, choices=[('barber', 'Barbero (Corte caballero)'), ('stylist', 'Estilista (Corte dama)'), ('manicurist', 'Manicurista'), ('pedicurist', 'Pedicurista'), ('colorist', 'Colorista'), ('braider', 'Trencista'), ('eyebrow', 'Cejas / Pestañas'), ('makeup', 'Maquilladora'), ('massage', 'Masajista'), ('barber_stylist', 'Barbero / Estilista'), ('general', 'General / Multipropósito'), ('other', 'Otro')], help_text='Profesión principal del empleado (ej.: barbero, estilista, manicurista, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialties',
            field=models.JSONField(default=list, help_text='Lista de especialidades adicionales o complejas (ej.: faena, balayage, etc.)'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['profession'], name='employees_a_profess_e8344b_idx'),
        ),
    ]
