# Generated by Django 5.2.11 on 2026-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_api', '0028_attendancerecord_late_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(default='personal_loan', max_length=20),
        ),
    ]
