# Generated by Django 5.2.11 on 2026-05-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_api', '0002_inappnotification'),
        ('tenants_api', '0010_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenants_api.tenant'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_template_name_per_tenant'),
        ),
    ]
