# Generated by Django 5.2.11 on 2026-07-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta del soporte'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
    ]
